server.port=8081
spring.application.name=users-service-develop

spring.datasource.url=jdbc:postgresql://users-db-develop:5432/usersdb_develop
spring.datasource.username=postgres
spring.datasource.password=yeison

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true